server:
  port: 8080

spring:
  application:
    name: user-service  # This will be used to register with Eureka

  datasource:
    url: jdbc:mysql://localhost:3306/user_1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update  # Use "validate" or "none" in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
